# -*- coding: utf-8 -*-
"""biofuel paper figures.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dPGzPC0xrJ0oi4XwaRF4nTa_bzObBYsx
"""

# Import libraries
from mpl_toolkits import mplot3d
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Importing data
df = pd.read_csv('/content/2022.06.29 (3, 13, 3, 4, 3, 2, 2).csv')
df = df.drop_duplicates()
x = df['z1']
y = df['z2']
z = df['z3']
# Creating dataset
#x = np.random.randint(80, size =(50))
#y = np.random.randint(60, size =(50))
#z = np.random.randint(100, size =(50))

# Creating figure
fig = plt.figure(figsize = (5.5,5.5))
ax = plt.axes(projection ="3d")
 
# Creating plot
plt.rcParams.update({'font.family':'Cambria'})

ax.scatter3D(x, y, z, color = "green", edgecolors ='green', s=50)
#plt.title("simple 3D scatter plot")
ax.set_xlabel('$Z_{1}$: Cost', fontsize=10, color = 'black')
ax.set_ylabel('$Z_{2}$: CO2e', color = 'black')
ax.set_zlabel('$Z_{3}$: Job', color = 'black')
plt.rcParams['font.size'] = '10'

ax.xaxis.pane.fill = False
ax.yaxis.pane.fill = False
ax.zaxis.pane.fill = False

ax.xaxis.set_tick_params(labelsize=8)
ax.yaxis.set_tick_params(labelsize=8)
ax.zaxis.set_tick_params(labelsize=8)

ax.w_xaxis.line.set_color("black")
ax.w_yaxis.line.set_color("black")
ax.w_zaxis.line.set_color("black")

# show plot
plt.savefig('saved_figure3.png')
plt.show()

# The second figure
fig = plt.figure(figsize = (3, 4))
plt.rcParams['font.size'] = '10'
#plt.title("Sales vs Prices for Orange Drinks and Cereal Bars")
#plt.legend(["Orange Drinks", "Cereal Bars"])
plt.xlabel('$Z_{1}$: Cost')
plt.ylabel('$Z_{2}$: CO2e')

plt.text(min(x),2800,"Marker size= '$Z_{3}$: Job'")


#plt.scatter(x, y, s=z, color = "green")
plt.scatter(x, y, s=z, color = "w",edgecolors ='green')
plt.show()